services:
  identra-grpc:
    image: ghcr.io/poly-workshop/identra-grpc:v0.1.5
    container_name: identra-grpc
    ports:
      - 50051:50051
    environment:
      PRESISTENCE_TYPE: gorm
      PRESISTENCE_GORM_DRIVER: postgres
      PRESISTENCE_GORM_HOST: localhost
      PRESISTENCE_GORM_PORT: 5432
      PRESISTENCE_GORM_USER: postgres
      PRESISTENCE_GORM_PASSWORD: postgres
      PRESISTENCE_GORM_DBNAME: identra

  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
